service: base-layer

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev

layers:
  base:
    path: dist
    name: base-layer-${sls:stage}
    compatibleRuntimes:
      - nodejs14.x

resources:
  Outputs:
    BaseLambdaLayer:
      Value:
        Ref: BaseLambdaLayer
      Export:
        Name: ${self:service}-${sls:stage}-BaseLambdaLayer
